# Change these first
owner: zeerx7 # Your GitHub organization or username, where this repository lives
repo: uptime-reverse-ip # The name of this repository

sites:
  - name: reverseipdomain.com
    url: https://reverseipdomain.com
  - name: api.reverseipdomain.com
    url: https://api.reverseipdomain.com
  - name: sub-scan-api.reverseipdomain.com
    url: https://sub-scan-api.reverseipdomain.com/?domain=amazonaws.com
  #- name: Google
  #  url: https://www.google.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.reverseipdomain.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: Reverseipdomain Status
  introMessage: This site is used to monitor the uptime of several services on reverseipdomain.com. We may not display the uptime of all the services we have.
  navbar:
    - title: Status
      href: /
    - title: Main Website
      href: https://reverseipdomain.com/
    - title: GitHub
      href: https://github.com/$OWNER/reverse-ip

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
